export const ROLES = {
  ADMIN: 'admin',         // Toàn quyền — CTO/Owner
  MANAGER: 'manager',     // CRM Manager (bạn) — xem tất cả + export
  CS: 'cs',               // CS Team — xem KH + task của mình
  SALES: 'sales'          // Sales Team — xem Opportunities + Customers
};

export const PERMISSIONS = {
  // Dashboard
  VIEW_DASHBOARD: [ROLES.ADMIN, ROLES.MANAGER, ROLES.CS, ROLES.SALES],
  VIEW_DASHBOARD_FULL: [ROLES.ADMIN, ROLES.MANAGER],  // Alert banner + Campaign widgets

  // Customers
  VIEW_CUSTOMERS: [ROLES.ADMIN, ROLES.MANAGER, ROLES.CS, ROLES.SALES],
  EDIT_CUSTOMER: [ROLES.ADMIN, ROLES.MANAGER, ROLES.CS],
  DELETE_CUSTOMER: [ROLES.ADMIN, ROLES.MANAGER],
  EXPORT_CUSTOMERS: [ROLES.ADMIN, ROLES.MANAGER],

  // Reports & Analysis
  VIEW_REPORTS: [ROLES.ADMIN, ROLES.MANAGER],
  VIEW_GROUP_IDS: [ROLES.ADMIN, ROLES.MANAGER],     // Restricted section
  VIEW_KPI_SCORECARD: [ROLES.ADMIN, ROLES.MANAGER],
  EXPORT_REPORTS: [ROLES.ADMIN, ROLES.MANAGER],

  // Opportunities (Sales pipeline)
  VIEW_OPPORTUNITIES: [ROLES.ADMIN, ROLES.MANAGER, ROLES.SALES],
  EDIT_OPPORTUNITY: [ROLES.ADMIN, ROLES.MANAGER, ROLES.SALES],
  DELETE_OPPORTUNITY: [ROLES.ADMIN, ROLES.MANAGER],

  // Marketing
  VIEW_MARKETING: [ROLES.ADMIN, ROLES.MANAGER],
  EDIT_CAMPAIGN: [ROLES.ADMIN, ROLES.MANAGER],

  // Analytics
  VIEW_ANALYTICS: [ROLES.ADMIN, ROLES.MANAGER],

  // Settings
  VIEW_SETTINGS: [ROLES.ADMIN, ROLES.MANAGER],
  MANAGE_USERS: [ROLES.ADMIN],
  MANAGE_ROLES: [ROLES.ADMIN],

  // Clients (B2B)
  VIEW_CLIENTS: [ROLES.ADMIN, ROLES.MANAGER, ROLES.SALES],
  EDIT_CLIENT: [ROLES.ADMIN, ROLES.MANAGER, ROLES.SALES],
};
